In [1]:
# buat matrix X berukuran 2x3 menggunakan numpy

In [2]:
import numpy as np

In [7]:
x = np.array([[14, 1, 4],
              [4, 1, 14]])
x

array([[14,  1,  4],
       [ 4,  1, 14]])

In [8]:
# tampilkan ukuran dari matrix X
x.shape

(2, 3)

In [9]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
x[:,0]

array([14,  4])

In [10]:
# tampilkan seluruh elemen dari baris kedua dari matrix X
x[1,:]

array([ 4,  1, 14])

In [19]:
#ulangi soal nomor 1 menggunakan pytorch
import torch as pt

In [20]:
# buat matrix X berukuran 2x3 menggunakan torch
x_pt = pt.tensor([[14, 1, 4],[4, 1, 14]])
x_pt

tensor([[14,  1,  4],
        [ 4,  1, 14]])

In [21]:
# tampilkan ukuran dari matrix X
x_pt.shape

torch.Size([2, 3])

In [22]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
x_pt[:,0]

tensor([14,  4])

In [23]:
# tampilkan seluruh elemen dari baris kedua dari matrix X
x_pt[1,:]

tensor([ 4,  1, 14])

In [11]:
# ulangi soal nomor 1 menggunakan tensorflow
import tensorflow as tf

In [14]:
# buat matrix X berukuran 2x3 menggunakan tensorflow
x_tf = tf.Variable([[14, 1, 4],[4, 1, 14]])
x_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[14,  1,  4],
       [ 4,  1, 14]], dtype=int32)>

In [15]:
# tampilkan ukuran dari matrix X
x_tf.shape

TensorShape([2, 3])

In [16]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
x_tf[:,0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([14,  4], dtype=int32)>

In [17]:
# tampilkan seluruh elemen dari baris kedua dari matrix X
x_tf[1,:]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 4,  1, 14], dtype=int32)>