In [ ]:
# buat vector x dengan ukuran 3x1

In [2]:
import numpy as np

In [3]:
x = np.array([[14],[ 1],[ 4]])
x

array([[14],
       [ 1],
       [ 4]])

In [10]:
# hitung nilai L2 norm dari vector x
np.linalg.norm(x)

np.float64(14.594519519326424)

In [11]:
# buat vector v dengan elemen (3,4)
v = np.array([3,4])
v


array([3, 4])

In [12]:
# hitung nilai L2 norm dari vector v
np.linalg.norm(v)

np.float64(5.0)

In [13]:
# tampilkan unit vector dari vector v
norm_v = np.linalg.norm(v)

In [14]:
unit_v = v/norm_v
unit_v

array([0.6, 0.8])

In [15]:
# hitung panjang unit vector dari vector v
panjang_unit_v = np.linalg.norm(unit_v)
panjang_unit_v

np.float64(1.0)