In [45]:
# buat vector x dengan ukuran 3x1
import numpy as np

x = np.array([[14],
              [1] ,
              [4]])
x

array([[14],
       [ 1],
       [ 4]])

In [46]:
# hitung panjang vector x
len(x)

3

In [47]:
# tampilkan ukuran vector x
x.shape

(3, 1)

In [48]:
# tampilkan tipe data dari vector x
type(x)

numpy.ndarray

In [49]:
# akses elemen pertama dari vector x
x[0]

array([14])

In [50]:
# tampilkan tipe data elemen pertama dari vector x
type(x[0])

numpy.ndarray

In [51]:
# lakukan transpose pada vector x dan simpan pada variabel x_t
x_t = x.T
x_t

array([[14,  1,  4]])

In [52]:
# tampilkan ukuran dari vector x_t
x_t.shape

(1, 3)

In [54]:
# lakukan transpose pada vector y dan simpan pada variabel y_t
y = np.array([[14],
              [1] ,
              [4]])
y

array([[14],
       [ 1],
       [ 4]])

In [55]:
y_t = y.T
y_t

array([[14,  1,  4]])

In [56]:
# tampilkan ukuran dari vector y_t
y_t.shape

(1, 3)

In [21]:
# lakukan soal nomor 2 menggunakan pytorch dan tensorflow

In [22]:
import torch as pt
import tensorflow as tf

In [57]:
# membuat vector x ukuran 3x1 menggunakan torch dan tensorflow
# torch
x_pt = pt.tensor([[14],
                  [1] ,
                  [4]])
x_pt

tensor([[14],
        [ 1],
        [ 4]])

In [59]:
 # tensorflow
x_tf = tf.Variable([[14],
              [1] ,
              [4]])
x_tf

<tf.Variable 'Variable:0' shape=(3, 1) dtype=int32, numpy=
array([[14],
       [ 1],
       [ 4]], dtype=int32)>

In [74]:
# lakukan transpose pada vector x dan simpan pada variabel x_t menggunakan torch dan tensorflow

In [75]:
#torch
x_pt_t = x_pt.T
x_pt_t

tensor([[14,  1,  4]])

In [76]:
 #tensorflow
x_tf_t = tf.transpose(x_tf)
x_tf_t

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[14,  1,  4]], dtype=int32)>

In [77]:
# tampilkan ukuran dari vector x_t menggunakan torch dan tensorflow


In [78]:
x_pt_t.shape #torch

torch.Size([1, 3])

In [80]:
x_tf_t.shape #tensorflow

TensorShape([1, 3])

In [ ]:
#lakukan transpose pada vector y dan simpan pada variabel y_t

In [82]:
y_pt = pt.tensor([[14],[1],[4]]) # torch
y_pt

tensor([[14],
        [ 1],
        [ 4]])

In [84]:
y_tf = tf.Variable([[14],[1],[4]]) # tensorflow
y_tf

<tf.Variable 'Variable:0' shape=(3, 1) dtype=int32, numpy=
array([[14],
       [ 1],
       [ 4]], dtype=int32)>

In [85]:
# transpose

In [86]:
y_pt_t = y_pt.T #torch
y_pt_t

tensor([[14,  1,  4]])

In [87]:
y_tf_t = tf.transpose(y_tf) #tensorflow
y_tf_t


<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[14,  1,  4]], dtype=int32)>

In [88]:
# tampilkan ukuran dari vector y_t menggunakan torch dan tensorflow

In [89]:
y_pt_t.shape #torch

torch.Size([1, 3])

In [90]:
y_tf_t.shape #tensorflow

TensorShape([1, 3])